---
apiVersion: v1
kind: Service
metadata:
  name: grape-and-pear
  labels:
    app.kubernetes.io/name: grape-and-pear
    app.kubernetes.io/instance: grape-and-pear
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: grape-and-pear
    app.kubernetes.io/instance: grape-and-pear

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grape-and-pear
  labels:
    app.kubernetes.io/name: grape-and-pear
    app.kubernetes.io/instance: grape-and-pear
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: kustomize
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grape-and-pear
      app.kubernetes.io/instance: grape-and-pear
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grape-and-pear
        app.kubernetes.io/instance: grape-and-pear
    spec:
      serviceAccountName: grape-and-pear
      containers:
        - name: grape-and-pear
          image: "docker.io/lunarfish/grape-and-pear:latest"
          ports:
            - containerPort: 80
